### ISSUE TITLE
The FAQ section  buttons animation is not correct , Change the animation of that and update the javascript code

### ISSUE THREAD

**Issue by Codetoadeath** [Codetoadeath/CodeForAll#1]
> Add custom plus cross buttons.
> make the transition of open and close smooth.
> Improve the over JavaScript.

**Comment by Digvijay2347** [comment]
Please assign this issue to  me @Codetoadeath

**Comment by Ayush05m** [comment]
Is this issue solved yet?
According to me, the current change made by @Digvijay2347 does not solve the problem.
If you feel unsatisfied with the current changes then reassign me this issue.

**Comment by Codetoadeath** [comment]
> Is this issue solved yet? According to me, the current change made by @Digvijay2347 does not solve the problem. If you feel unsatisfied with the current changes then reassign me this issue.

sure , but the code should be perfect and it should be responsive

**Comment by Codetoadeath** [comment]
> Is this issue solved yet? According to me, the current change made by @Digvijay2347 does not solve the problem. If you feel unsatisfied with the current changes then reassign me this issue.

Make sure to Star our Repo

**Comment by vishal-sharma-369** [comment]
I have solved the issue with smooth transition effectts for the toggle buttons and the answer sections
Attached below is my PR

**Comment by rituraj12797** [comment]
please assign me this issue i can work on this @Codetoadeath

**Comment by Codetoadeath** [comment]
> please assign me this issue i can work on this @Codetoadeath

Sure , But make sure to Star our Repo
