### ISSUE TITLE
Create a Blog section which has  Responsive Caraousel using (HTML, CSS, Js) 

### ISSUE THREAD

**Issue by Codetoadeath** [Codetoadeath/CodeForAll#3]
Use Help of this URL:- https://codepen.io/dev_loop/pen/MWKbJmO

> The code should be only in - HTML, CSS , Javascript . No other type will work .  
> Make sure to Star our Repo first .
> Code   will only be merged after successful operation of the desired program
> The code nearest to above url will be merged 

![image](https://github.com/Codetoadeath/CodeForAll/assets/144260114/65bcc422-9c46-42f7-a8f4-53b31f28fa3d)

**Comment by Codetoadeath** [comment]
> @Codetoadeath I hope you're doing well. I'm Pragya Mishra, working as a Front-end developer and I'm excited about this project. This would be my first time hactoberfest contribution to an open-source project, and I'm eager to get started. I've been looking through the issues. It seems like a great start for me to learn and contribute to this project. Could I take on this issue? I'm more than willing to put in the effort and would greatly appreciate your guidance on how to proceed. Thanks a lot for your time and consideration!

Thats great , Make sure you star our Repository.     i'll assign this issue to you.

**Comment by rituraj12797** [comment]
@Codetoadeath  assign it to me as well i also want to work on this issue

**Comment by Codetoadeath** [comment]
> @Codetoadeath assign it to me as well i also want to work on this issue

Make sure to star our repository

**Comment by pragyamishra56** [comment]
@Codetoadeath Sir could you assist me How to resolve to this issue means You want a blog but where on the image with responsive?

**Comment by Codetoadeath** [comment]
> @Codetoadeath Sir could you assist me How to resolve to this issue means You want a blog but where on the image with responsive?

Nahh , the blogs will be on a seperate page , but when clicked on these Caraousal , it open the blog in a different page, that should be a blog page. But you should focus on this only , blog page u don't have to make

**Comment by rituraj12797** [comment]
sir most of the part is done sending you the ss

**Comment by rituraj12797** [comment]
a little bit of butotn styling and text editing is all that's left rest is done 


https://github.com/Codetoadeath/CodeForAll/assets/120770641/ef6296b7-7fc7-405f-88dd-019f68848f73

**Comment by pragyamishra56** [comment]
@Codetoadeath Sir @rituraj12797 already done with this issue then what should I do

**Comment by Codetoadeath** [comment]
> a little bit of butotn styling and text editing is all that's left rest is done
> 
>  dudu.mp4

if you completed, that create a pull request , that I can merge

**Comment by Codetoadeath** [comment]
> @Codetoadeath Sir @rituraj12797 already done with this issue then what should I do

You should also submit

**Comment by rituraj12797** [comment]
done
