### ISSUE TITLE
React Project-Responsive Paragraph Word Counter

### ISSUE THREAD

**Issue by Codetoadeath** [Codetoadeath/CodeForAll#9]
![image](https://github.com/Codetoadeath/CodeForAll/assets/144260114/ba0314fb-a676-4878-9e7e-309979841983)

**Comment by soumyadeep-deb** [comment]
Hey @Codetoadeath can you please assign this issue to me?

**Comment by soumyadeep-deb** [comment]
Hey @Codetoadeath 
I have starred the repository, implemented this word-counter website using react and also added description on how to run the project.
Finally, I have raise a Pull request, please review it when you get some time.
